require ("prototypes.scripts.defines")

require("prototypes.categories.discharge-fluids")
require("prototypes.item.discharge-pump")
require("prototypes.item.pipes")
require("prototypes.item.valves")
require("prototypes.recipe.pipes")
require("prototypes.recipe.discharge-pump")
require("prototypes.entity.discharge-pump")
require("prototypes.entity.pipes")
require("prototypes.technology.discharge-pump")
require("prototypes.technology.pipes")